name: Mac testing

on:
  push:
    branches: [ smolsky/testing ]

jobs:
  build:
    name: Set up environment
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install librdkafka
      run: brew install librdkafka

  install-and-test:
    name: Install snews_pt and unit test
    runs-on: macos-11

    uses: SNEWS2/SNEWS_Publishing_Tools/.github/workflows/unit-tests.yml@smolsky/testing
    with:
      system: macos-11