name: Shell testing

on:
  push:
    branches: [ smolsky/testing ]

jobs:
  build:
    runs-on: macos-11

    steps:
    - shell: bash
      env:
        username: joe
        password: password
      run: |
        echo $env.username
        echo $env.password